// <auto-generated />
namespace Blog.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _190220208 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_190220208));
        
        string IMigrationMetadata.Id
        {
            get { return "202002191947256_19022020-8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
